- name: Install Xdebug
  apt: pkg='php-xdebug' state=present

- name: Write Xdebug config
  template: src=xdebug.ini.j2 dest='/etc/php/{{ php_version }}/mods-available/xdebug.ini' owner=root group=root mode=0644

- name: Configure PHP to use Xdebug.
  file: src='/etc/php/{{ php_version }}/mods-available/xdebug.ini' dest='/etc/php/{{ php_version }}/cli/conf.d/20-xdebug.ini' state=link

- name: Configure PHP FPM to use Xdebug.
  file: src='/etc/php/{{ php_version }}/mods-available/xdebug.ini' dest='/etc/php/{{ php_version }}/fpm/conf.d/20-xdebug.ini' state=link
